### ISSUE TITLE
Missing ref for some buttons

### ISSUE THREAD

**Issue by maxbogo** [maxbogo/maxbogo.github.io#3]
**Describe the bug**
"Learn more" and "Download now" buttons should link right palces

**To Reproduce**
1. Go to https://maxbogo.github.io./
2. Click on "Learn more" or  "Download now"
3. Nothing happens

**Expected behavior**
"Learn more"  ref to  About Us  part 
"Download now"  ref to Subscribe part

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by julianschnee42** [comment]
the buttons in question were removed as a part of major content changes, so this isn't an issue anymore
